### 06.할일 등록
POST http://localhost:8080/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXIyIiwiaWF0IjoxNzQ3MTc1ODc5LCJleHAiOjE3NDcxNzk0Nzl9.kptXuVw9wCvO-wupJfzGOh74y-Zz1FYnA4N43AU7aQw
Content-Type: application/json

{
  "title": "할일5",
  "description": "할일5",
  "completed": false,
  "dueDate": "2025-05-15 02:00:00"
}

### 07.할일 전체 조회
GET http://localhost:8080/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXIyIiwiaWF0IjoxNzQ3MTc1ODc5LCJleHAiOjE3NDcxNzk0Nzl9.kptXuVw9wCvO-wupJfzGOh74y-Zz1FYnA4N43AU7aQw

### 08.할일 조회
GET http://localhost:8080/todos/7
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXIyIiwiaWF0IjoxNzQ3MTc1ODc5LCJleHAiOjE3NDcxNzk0Nzl9.kptXuVw9wCvO-wupJfzGOh74y-Zz1FYnA4N43AU7aQw

### 09.할일 수정
PUT http://localhost:8080/todos/7
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXIyIiwiaWF0IjoxNzQ3MTc1ODc5LCJleHAiOjE3NDcxNzk0Nzl9.kptXuVw9wCvO-wupJfzGOh74y-Zz1FYnA4N43AU7aQw
Content-Type: application/json

{
  "title": "할일5_1",
  "description": "할일5_1",
  "completed": true,
  "dueDate": "2025-05-15 02:00:00"
}

### 10.할일 삭제
DELETE http://localhost:8080/todos/7
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXIyIiwiaWF0IjoxNzQ3MTc1ODc5LCJleHAiOjE3NDcxNzk0Nzl9.kptXuVw9wCvO-wupJfzGOh74y-Zz1FYnA4N43AU7aQw

### 11.할일 검색
GET http://localhost:8080/todos/search?title=할일&description=&completed=false&dueStartDate=2025-05-10&dueEndDate=2025-05-15
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXIyIiwiaWF0IjoxNzQ3MTc1ODc5LCJleHAiOjE3NDcxNzk0Nzl9.kptXuVw9wCvO-wupJfzGOh74y-Zz1FYnA4N43AU7aQw
Content-Type: application/json
