### 투두 리스트 등록
POST http://localhost:8080/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXIyIiwiaWF0IjoxNzQ3MDQyMzc0LCJleHAiOjE3NDcwNDU5NzR9.-whGQWDf0Pn6R6z2tvjDFB5kkmLb9Hy8sKCPqiPXCqo
Content-Type: application/json

{
  "title": "네번째 할일",
  "description": "공부2 하기",
  "completed": false,
  "dueDate": "2025-05-13 02:00:00"
}

### 투두 리스트 전체 조회
GET http://localhost:8080/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXIyIiwiaWF0IjoxNzQ3MDU2Mjk0LCJleHAiOjE3NDcwNTk4OTR9.WQohFVv5oSzFkuG9blQ6fEW9b2i7SFRjeNQ2lm6mHpY

### 투두 리스트 조회
GET http://localhost:8080/todos/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXIyIiwiaWF0IjoxNzQ3MDU2Mjk0LCJleHAiOjE3NDcwNTk4OTR9.WQohFVv5oSzFkuG9blQ6fEW9b2i7SFRjeNQ2lm6mHpY

### 투두 리스트 수정
PUT http://localhost:8080/todos/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXIyIiwiaWF0IjoxNzQ3MDU2Mjk0LCJleHAiOjE3NDcwNTk4OTR9.WQohFVv5oSzFkuG9blQ6fEW9b2i7SFRjeNQ2lm6mHpY
Content-Type: application/json

{
  "title": "수정",
  "description": "테스트",
  "completed": true,
  "dueDate": "2025-05-13 03:00:00"
}

### 투두 리스트 삭제
DELETE http://localhost:8080/todos/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXIyIiwiaWF0IjoxNzQ3MDQ5MDEwLCJleHAiOjE3NDcwNTI2MTB9.4I2gF90GEUmCTr8qEl7HYKGsksBnkOnDTrbMbg1Qj9o

### 투두 리스트 검색
GET http://localhost:8080/todos/search?title=수정&description=테스트&completed=true&dueStartDate=2025-05-13&dueEndDate=2025-05-13
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXIyIiwiaWF0IjoxNzQ3MDU2Mjk0LCJleHAiOjE3NDcwNTk4OTR9.WQohFVv5oSzFkuG9blQ6fEW9b2i7SFRjeNQ2lm6mHpY
Content-Type: application/json
