### 01.회원가입
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "userId": "tester5",
  "userName": "테스터5",
  "password": "1234",
  "email": "tester5@gmail.com"
}

### 02.로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "userId": "tester5",
  "password": "1234"
}

### 03.내정보 조회
GET http://localhost:8080/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXI3IiwiaWF0IjoxNzQ3MTYwNjA2LCJleHAiOjE3NDcxNjQyMDZ9.HixLqnejWGC2P-WlX1pxyrVCCV333DCIB9tqsHs86Kk

### 04.내정보 수정
PUT http://localhost:8080/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXI1IiwiaWF0IjoxNzQ3MTcxNzUwLCJleHAiOjE3NDcxNzUzNTB9.nv4LLYYeRYFuJdDo3gPNSsNB1IbbNKMUbEySo9VKNuo
Content-Type: application/json

{
  "email": "tester5_1@gmail.com",
  "password": "1234",
  "userName": "테스터5_1"
}

### 05.계정 삭제
DELETE http://localhost:8080/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXI1IiwiaWF0IjoxNzQ3MTcxNzUwLCJleHAiOjE3NDcxNzUzNTB9.nv4LLYYeRYFuJdDo3gPNSsNB1IbbNKMUbEySo9VKNuo
Content-Type: application/json